- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/gemini.png"
  agent_id: "llm/vertex_ai/gemini-3-pro-preview"
  display_name: "gemini-3-pro"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "vertex_ai/gemini-3-pro-preview"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/deepseek.png"
  agent_id: "llm/openrouter/deepseek/deepseek-v3.2-speciale"
  display_name: "deepseek-v3.2-speciale"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/deepseek/deepseek-v3.2-speciale"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/openai.png"
  agent_id: "llm/openrouter/openai/gpt-5.1"
  display_name: "gpt-5.1"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/openai/gpt-5.1"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/qwen.png"
  agent_id: "llm/openrouter/qwen/qwen3-max"
  display_name: "qwen3-max"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/qwen/qwen3-max"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/kimi.png"
  agent_id: "llm/openrouter/moonshotai/kimi-k2-thinking"
  display_name: "kimi-k2-thinking"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/moonshotai/kimi-k2-thinking"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/zai.svg"
  agent_id: "llm/openrouter/z-ai/glm-4.6"
  display_name: "glm-4.6"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/z-ai/glm-4.6"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/anthropic.png"
  agent_id: "llm/openrouter/anthropic/claude-opus-4.5"
  display_name: "claude-opus-4.5"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/anthropic/claude-opus-4.5"
- thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/grok.png"
  agent_id: "llm/openrouter/x-ai/grok-4-fast"
  display_name: "grok-4-fast"
  agent_harness_name: "llm_harness"
  llms:
    - model_name: "openrouter/x-ai/grok-4-fast"