# Settings for the dump_audio.py script
script_settings:
  server:
    port: 7999
  paths:
    audio_dir_name: "audio"
    debug_audio_dir_name: "debug_audio"
    output_html_filename: "replay.html"
  voices:
    moderator: "enceladus"
    players:
      gemini-2.5-flash: 'Kore'
      deepseek-r1: 'Charon'
      gpt-oss-120b: 'Leda'
      qwen3: 'Despina'
      "gpt-4.1": 'Erinome'
      "o4-mini": 'Gacrux'
      "gemini-2.5-pro": 'Achird'
      "grok-4": 'Puck'
  audio:
    static_moderator_messages:
      night_begins: "(rate=\"fast\", volume=\"soft\", voice=\"mysterious\")[As darkness descends, the village falls silent.](rate=\"medium\", pitch=\"-2st\")[Everyone, close your eyes.]"
      day_begins: "(rate=\"fast\", volume=\"loud\")[Wake up, villagers!] (rate=\"medium\", voice=\"neutral\")[The sun rises on a new day.] (break=\"50ms\") (rate=\"medium\", voice=\"somber\")[Let's see who survived the night.]"
      discussion_begins: "(voice=\"authoritative\")[The town meeting now begins.] (voice=\"neutral\")[You have a few minutes to discuss and find the werewolves among you.] (voice=\"authoritative\")[Begin.]"
      voting_begins: "(rate=\"slow\", voice=\"serious\")[The time for talk is over.] (break=\"50ms\") (rate=\"medium\", volume=\"loud\", voice=\"dramatic\")[Now, you must cast your votes!]"

# Configuration for the Werewolf game environment
game_config:
  actTimeout: 300
  runTimeout: 3600
  discussion_protocol:
    name: "RoundRobinDiscussion"
    params:
      max_rounds: 1
  agents:
    - role: "Werewolf"
      id: "gemini-2.5-pro"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/gemini.png"
      agent_id: "llm/gemini/gemini-2.5-pro"
      display_name: "gemini/gemini-2.5-pro"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "gemini/gemini-2.5-pro"
    - role: "Werewolf"
      id: "deepseek-r1"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/deepseek.png"
      agent_id: "llm/together_ai/deepseek-ai/DeepSeek-R1"
      display_name: "together_ai/deepseek-ai/DeepSeek-R1"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "together_ai/deepseek-ai/DeepSeek-R1"
          parameters: { "max_tokens": 163839 }
    - role: "Doctor"
      id: "gpt-5"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/openai.png"
      agent_id: "llm/gpt-5"
      display_name: "gpt-5"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "gpt-5"
    - role: "Seer"
      id: "qwen3"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/qwen.png"
      agent_id: "llm/together_ai/Qwen/Qwen3-235B-A22B-Instruct-2507-tput"
      display_name: "together_ai/Qwen/Qwen3-235B-A22B-Instruct-2507-tput"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "together_ai/Qwen/Qwen3-235B-A22B-Instruct-2507-tput"
    - role: "Villager"
      id: "claude-4-sonnet"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/anthropic.png"
      agent_id: "llm/claude-4-sonnet-20250514"
      display_name: "claude-4-sonnet-20250514"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "claude-4-sonnet-20250514"
    - role: "Villager"
      id: "zai-glm-4.5-air"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/zai.svg"
      agent_id: "llm/together_ai/zai-org/GLM-4.5-Air-FP8"
      display_name: "zai-glm-4.5-air"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "together_ai/zai-org/GLM-4.5-Air-FP8"
          parameters: { "max_tokens": 100000 }
    - role: "Villager"
      id: "kimi-k2"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/kimi.png"
      agent_id: "llm/together_ai/moonshotai/Kimi-K2-Instruct"
      display_name: "kimi-k2"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "together_ai/moonshotai/Kimi-K2-Instruct"
          parameters: { "max_tokens": 100000 }
    - role: "Villager"
      id: "grok-4"
      thumbnail: "https://storage.googleapis.com/kaggle-static/game-arena/werewolf/thumbnails/grok.png"
      agent_id: "llm/xai/grok-4-latest"
      display_name: "xai/grok-4-latest"
      agent_harness_name: "llm_harness"
      llms:
        - model_name: "xai/grok-4-latest"